### ISSUE TITLE
Kanban review

### ISSUE THREAD

**Issue by MenendezON** [MenendezON/NYM-Capstone#23]
In this group, we're two (2) of us :
- Ye Min Thu
- Menendez NELSON

Link :  https://github.com/MenendezON/NYM-Capstone/projects/1

**Comment by Lizdev-05** [comment]
Hi @MenendezON  and @mryeminthu  , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/YYht2UTV41u1vxHTss/giphy-downsized-medium.gif"/>

## Highlights
:heavy_check_mark: Descriptive issue:+1: 

## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly ensure that cards are assigned to team members in a fair way:
    * First you need to decide who is `Student A`, and `Student B`. So each card with `Student A` in its title should always be assigned to the same student (and analogical for other students).
    * All cards with `group task` in the title should be assigned to someone (it does not matter to whom as students had freedom with that).

You should see a circle with the user's avatar on each card after assigning the cards to team members. See the example below:

  ![image](https://github.com/Yulianav09/Group-capstone/assets/73854999/ef6b9e5d-a358-4afe-883d-98a637ba7bb8)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by algerina** [comment]
Hi team,

Great job so far you can start working on your project!  

May I highlight the following: 
- [x] Your Kanbam board is setup correctly👏  ✔️ 
- [x] You implemented all the requirements✔️ 


## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:

Your project is complete!  It's time to merge it :shipit:

<img src="https://media4.giphy.com/media/tIeCLkB8geYtW/giphy.gif"/>

 
 ## Optional suggestions

 - Please check the comment under the review.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread and tag me @algerina if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [Algerina](https://github.com/algerina), I will receive a notification and will respond._

[GitHub](https://github.com/algerina) | [LinkedIn](https://linkedin.com/in/amel-khiri) | [Twitter](https://twitter.com/AmelQahwadji)

_Reviewed by [Amel Khiri ](https://github.com/algerina)_
